package com.hcy.entiry;

import java.util.Date;

public class admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPwd
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String adminpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.realName
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.telephone
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Email
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.birthday
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.sex
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.pic
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.remark
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPwd
     *
     * @return the value of admin.adminPwd
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getAdminpwd() {
        return adminpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPwd
     *
     * @param adminpwd the value for admin.adminPwd
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setAdminpwd(String adminpwd) {
        this.adminpwd = adminpwd == null ? null : adminpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.realName
     *
     * @return the value of admin.realName
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.realName
     *
     * @param realname the value for admin.realName
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.telephone
     *
     * @return the value of admin.telephone
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.telephone
     *
     * @param telephone the value for admin.telephone
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Email
     *
     * @return the value of admin.Email
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Email
     *
     * @param email the value for admin.Email
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.birthday
     *
     * @return the value of admin.birthday
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.birthday
     *
     * @param birthday the value for admin.birthday
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.pic
     *
     * @return the value of admin.pic
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.pic
     *
     * @param pic the value for admin.pic
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.remark
     *
     * @return the value of admin.remark
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.remark
     *
     * @param remark the value for admin.remark
     *
     * @mbggenerated Sun Mar 01 13:49:17 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}